spring.application.name=SPRING-SKELTON-APP
#spring.config.import=optional:consul:
appconfig.application=springbootskeltonapp
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.username=
spring.datasource.hikari.password=
spring.driver-class-name=org.postgresql.Driver
spring.cloud.discovery.client.composite-indicator.enabled=false
feign.client.config.default.errorDecoder=com.coredigital.accountsservice.config.feign.client.FeignClientErrorDecoder
feign.client.config.default.retryer=com.coredigital.accountsservice.config.feign.client.FeignClientRetryer
spring.cloud.config.enabled=true
spring.datasource.hikari.driverRequest-class-name=org.postgresql.Driver
logging.level.com.coredigital=INFO
#spring.jpa.properties.hibernate.default_schema=pawan
appconfig.application=springbootskeltonapp




