# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with ECS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: DEV
    permissions: 
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Setup Terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v2
      with:
         terraform_version: 1.4.6
    - name: Build with Maven
      run: mvn clean install
    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1 
      with: 
        role-to-assume: arn:aws:iam::928173699427:role/GITHUB_ASSUME_ROLE
        role-session-name: springskeltonapp-session
        aws-region: us-west-2 
    - name: Apply Terraform 
      id: apply-terraform 
      working-directory: ./terraform
      run: | 
        echo "Applying Terraform" 
        terraform init -backend-config="bucket=pawansd-terraform-state-files" -backend-config="key=springbootskeltonapp" -backend-config="region=us-west-2"
    - name: Build, tag, and push image to Amazon ECR 
      id: build-image 
      run: | 
        echo "Building container image" 
        echo ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:${{ vars.IMAGE_TAG }} 
        docker build -t ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:${{ vars.IMAGE_TAG }} . 
        docker push ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:${{ vars.IMAGE_TAG }} 
    

